2012/03/23 15:53:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('gii')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/?r=gii
2012/03/23 15:59:58 [error] [exception.CException] exception 'CException' with message 'IndexController does not have a method named "renderPartail".' in E:\pro\xampp\htdocs\yii\framework\base\CComponent.php:266
Stack trace:
#0 E:\pro\xampp\htdocs\cms\admin\protected\controllers\IndexController.php(7): CComponent->__call('renderPartail', Array)
#1 E:\pro\xampp\htdocs\cms\admin\protected\controllers\IndexController.php(7): IndexController->renderPartail('index')
#2 E:\pro\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): IndexController->actionIndex()
#3 E:\pro\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#4 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#5 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CController->run('')
#7 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('')
#8 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#9 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#10 {main} REQUEST_URI=/cms/admin/index.php
2012/03/23 16:06:31 [error] [exception.CException] exception 'CException' with message 'Property "IndexController.baseUrl" is not defined.' in E:\pro\xampp\htdocs\yii\framework\base\CComponent.php:131
Stack trace:
#0 E:\pro\xampp\htdocs\cms\admin\protected\views\index\index.php(2): CComponent->__get('baseUrl')
#1 E:\pro\xampp\htdocs\yii\framework\web\CBaseController.php(119): require('E:\pro\xampp\ht...')
#2 E:\pro\xampp\htdocs\yii\framework\web\CBaseController.php(88): CBaseController->renderInternal('E:\pro\xampp\ht...', NULL, true)
#3 E:\pro\xampp\htdocs\yii\framework\web\CController.php(866): CBaseController->renderFile('E:\pro\xampp\ht...', NULL, true)
#4 E:\pro\xampp\htdocs\cms\admin\protected\controllers\IndexController.php(7): CController->renderPartial('index')
#5 E:\pro\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): IndexController->actionIndex()
#6 E:\pro\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#7 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#8 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CController->run('')
#10 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('')
#11 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#12 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#13 {main} REQUEST_URI=/cms/admin/index.php
2012/03/25 17:17:24 [error] [php] Undefined variable: _SESSION (E:\pro\xampp\htdocs\cms\admin\protected\controllers\SiteController.php:2)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/?r=site
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\SiteController.php (2)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/03/25 17:18:06 [error] [php] Undefined variable: _SESSION (E:\pro\xampp\htdocs\cms\admin\protected\controllers\SiteController.php:2)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/?r=site
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\SiteController.php (2)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/03/28 15:33:37 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cms.wf_category' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `wf_category`.
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/03/29 15:29:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "category".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('category')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=category
2012/03/29 16:27:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 16:28:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 16:29:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 16:30:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 16:31:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 16:31:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 16:33:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 16:34:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 16:34:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 16:35:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 16:35:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 16:35:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 16:54:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 16:54:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 16:55:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 16:55:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "add".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('add')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=add
2012/03/29 16:55:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 16:56:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 16:56:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "add".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('add')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=add
2012/03/29 16:56:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 16:57:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 16:57:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 16:57:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "add".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('add')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=add
2012/03/29 17:00:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:00:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:00:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "add".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('add')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=add
2012/03/29 17:00:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:09:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:09:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "add".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('add')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=add
2012/03/29 17:09:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:12:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:12:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "add".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('add')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=add
2012/03/29 17:12:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:12:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:12:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "add".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('add')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=add
2012/03/29 17:12:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:12:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:12:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "add".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('add')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=add
2012/03/29 17:12:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:12:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "add".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('add')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=add
2012/03/29 17:12:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:12:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "add".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('add')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=add
2012/03/29 17:13:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "add".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('add')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=add
2012/03/29 17:13:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:13:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:13:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "add".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('add')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=add
2012/03/29 17:13:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:13:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:13:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:13:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "add".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('add')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=add
2012/03/29 17:15:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:15:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:15:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "add".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('add')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=add
2012/03/29 17:18:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:18:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:18:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "category/list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('category/list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=category/list
2012/03/29 17:18:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:18:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:18:41 [error] [php] Undefined variable: models (E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php:14)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CategorysController->runAction()
#1 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CategorysController->runActionWithFilters()
#2 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CategorysController->run()
#3 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#4 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#5 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/index.php?r=categorys/list
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (14)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/03/29 17:19:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:33:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:33:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:33:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:33:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "category/list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('category/list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=category/list
2012/03/29 17:34:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:34:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "category/list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('category/list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=category/list
2012/03/29 17:34:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:34:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:34:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/29 17:34:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "category/list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('category/list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=category/list
2012/03/30 15:17:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:17:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:21:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:21:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:22:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:24:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:26:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:27:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:28:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:28:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:29:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:29:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:41:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:41:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:42:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:42:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:43:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:44:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:44:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:45:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:56:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:57:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:58:18 [error] [exception.CException] exception 'CException' with message 'CategorysController cannot find the requested view "post".' in E:\pro\xampp\htdocs\yii\framework\web\CController.php:875
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(779): CController->renderPartial('post', NULL, true)
#1 E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php(20): CController->render('post')
#2 E:\pro\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): CategorysController->actionPost()
#3 E:\pro\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#4 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#5 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CController->run('post')
#7 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('categorys/post')
#8 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#9 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#10 {main} REQUEST_URI=/cms/admin/index.php?r=categorys/post
2012/03/30 15:59:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 15:59:41 [error] [php] Undefined variable: model (E:\pro\xampp\htdocs\cms\admin\protected\views\categorys\post.php:10)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(866): CategorysController->renderFile()
#1 E:\pro\xampp\htdocs\yii\framework\web\CController.php(779): CategorysController->renderPartial()
#2 E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php(40): CategorysController->render()
#3 E:\pro\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): CategorysController->actionPost()
#4 E:\pro\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams()
#5 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CategorysController->runAction()
#6 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CategorysController->runActionWithFilters()
#7 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CategorysController->run()
#8 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#9 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#10 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/index.php?r=categorys/post
in E:\pro\xampp\htdocs\cms\admin\protected\views\categorys\post.php (10)
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (40)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/03/30 15:59:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:01:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:01:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:01:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:02:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:02:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:02:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:02:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:02:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:02:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:02:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:02:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:02:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:03:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:11:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:13:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:14:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:15:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:16:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:30:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:31:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:31:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:32:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:35:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:40:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:43:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:45:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:54:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:55:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:55:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:55:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 16:55:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:03:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:04:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:04:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:04:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:04:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:05:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:05:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:05:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:05:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:05:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:05:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:05:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:05:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:05:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:05:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:11:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:14:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:14:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:14:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:14:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:14:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:15:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:15:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:15:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:15:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:15:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/30 17:15:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/03/31 17:38:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/04/05 16:07:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/04/05 16:08:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/04/05 16:12:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/04/05 16:24:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/04/05 16:25:57 [error] [exception.CException] exception 'CException' with message 'Property "Categorys.id" is not defined.' in E:\pro\xampp\htdocs\yii\framework\base\CComponent.php:131
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(128): CComponent->__get('id')
#1 E:\pro\xampp\htdocs\cms\admin\protected\models\Categorys.php(81): CActiveRecord->__get('id')
#2 E:\pro\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1009): Categorys->beforeSave()
#3 E:\pro\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(779): CActiveRecord->insert(NULL)
#4 E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php(36): CActiveRecord->save()
#5 E:\pro\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): CategorysController->actionPost()
#6 E:\pro\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#7 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#8 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CController->run('post')
#10 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('categorys/post')
#11 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#12 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#13 {main} REQUEST_URI=/cms/admin/index.php?r=categorys/post
2012/04/05 16:26:20 [error] [exception.CException] exception 'CException' with message 'Property "Categorys.id" is not defined.' in E:\pro\xampp\htdocs\yii\framework\base\CComponent.php:131
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(128): CComponent->__get('id')
#1 E:\pro\xampp\htdocs\cms\admin\protected\models\Categorys.php(81): CActiveRecord->__get('id')
#2 E:\pro\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1035): Categorys->afterSave()
#3 E:\pro\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(779): CActiveRecord->insert(NULL)
#4 E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php(36): CActiveRecord->save()
#5 E:\pro\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): CategorysController->actionPost()
#6 E:\pro\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#7 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#8 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CController->run('post')
#10 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('categorys/post')
#11 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#12 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#13 {main} REQUEST_URI=/cms/admin/index.php?r=categorys/post
2012/04/05 16:26:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/04/05 16:27:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/04/05 16:28:18 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '6' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `wf_categorys` (`parent`, `title`, `notes`, `url`, `cid`, `tree`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
in E:\pro\xampp\htdocs\cms\admin\protected\models\Categorys.php (83)
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (36)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/04/05 16:28:18 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '6' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `wf_categorys` (`parent`, `title`, `notes`, `url`, `cid`, `tree`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)' in E:\pro\xampp\htdocs\yii\framework\db\CDbCommand.php:338
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1015): CDbCommand->execute()
#1 E:\pro\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(779): CActiveRecord->insert(NULL)
#2 E:\pro\xampp\htdocs\cms\admin\protected\models\Categorys.php(83): CActiveRecord->save()
#3 E:\pro\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1035): Categorys->afterSave()
#4 E:\pro\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(779): CActiveRecord->insert(NULL)
#5 E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php(36): CActiveRecord->save()
#6 E:\pro\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): CategorysController->actionPost()
#7 E:\pro\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#9 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CController->run('post')
#11 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('categorys/post')
#12 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#13 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#14 {main} REQUEST_URI=/cms/admin/index.php?r=categorys/post
2012/04/05 16:30:56 [error] [php] Object of class Categorys could not be converted to string (E:\pro\xampp\htdocs\cms\admin\protected\models\Categorys.php:82)
Stack trace:
#0 E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php(36): Categorys->save()
#1 E:\pro\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): CategorysController->actionPost()
#2 E:\pro\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams()
#3 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CategorysController->runAction()
#4 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CategorysController->runActionWithFilters()
#5 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CategorysController->run()
#6 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#7 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#8 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/index.php?r=categorys/post
in E:\pro\xampp\htdocs\cms\admin\protected\models\Categorys.php (82)
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (36)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/04/05 16:34:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/04/05 16:34:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/04/05 16:34:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/04/05 16:38:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/04/05 16:47:00 [error] [php] Object of class Categorys could not be converted to string (E:\pro\xampp\htdocs\yii\framework\web\helpers\CHtml.php:1869)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\widgets\CActiveForm.php(689): activeListBox()
#1 E:\pro\xampp\htdocs\cms\admin\protected\views\categorys\post.php(22): CActiveForm->listBox()
#2 E:\pro\xampp\htdocs\yii\framework\web\CBaseController.php(119): require()
#3 E:\pro\xampp\htdocs\yii\framework\web\CBaseController.php(88): CategorysController->renderInternal()
#4 E:\pro\xampp\htdocs\yii\framework\web\CController.php(866): CategorysController->renderFile()
#5 E:\pro\xampp\htdocs\yii\framework\web\CController.php(779): CategorysController->renderPartial()
#6 E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php(43): CategorysController->render()
#7 E:\pro\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): CategorysController->actionPost()
#8 E:\pro\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams()
#9 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CategorysController->runAction()
#10 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CategorysController->runActionWithFilters()
#11 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CategorysController->run()
#12 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#13 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#14 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/index.php?r=categorys/post
in E:\pro\xampp\htdocs\cms\admin\protected\views\categorys\post.php (22)
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (43)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/04/05 16:50:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/04/05 16:53:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/04/05 16:57:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/04/05 17:23:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/04/05 17:23:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/04/05 17:29:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list".' in E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('list')
#1 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/cms/admin/index.php?r=list
2012/04/06 16:47:33 [error] [php] Undefined variable: currentPage (E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php:15)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CategorysController->runAction()
#1 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CategorysController->runActionWithFilters()
#2 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CategorysController->run()
#3 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#4 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#5 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/index.php?r=categorys/list
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (15)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/04/06 16:56:43 [error] [php] Undefined index: sortname (E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php:19)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CategorysController->runAction()
#1 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CategorysController->runActionWithFilters()
#2 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CategorysController->run()
#3 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#4 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#5 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/index.php?r=categorys/list
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (19)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/04/06 16:56:45 [error] [php] Undefined index: sortname (E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php:19)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CategorysController->runAction()
#1 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CategorysController->runActionWithFilters()
#2 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CategorysController->run()
#3 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#4 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#5 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/index.php?r=categorys/list
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (19)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/04/06 16:57:01 [error] [php] Undefined index: sortname (E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php:19)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CategorysController->runAction()
#1 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CategorysController->runActionWithFilters()
#2 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CategorysController->run()
#3 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#4 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#5 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/index.php?r=categorys/list
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (19)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/04/06 16:57:18 [error] [php] Undefined index: sortname (E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php:19)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CategorysController->runAction()
#1 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CategorysController->runActionWithFilters()
#2 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CategorysController->run()
#3 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#4 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#5 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/index.php?r=categorys/list
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (19)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/04/06 16:57:24 [error] [php] Undefined index: sortname (E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php:19)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CategorysController->runAction()
#1 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CategorysController->runActionWithFilters()
#2 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CategorysController->run()
#3 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#4 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#5 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/index.php?r=categorys/list
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (19)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/04/06 17:21:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "remove".' in E:\pro\xampp\htdocs\yii\framework\web\CController.php:477
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(262): CController->missingAction('remove')
#1 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CController->run('remove')
#2 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('categorys/remov...')
#3 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#4 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/cms/admin/index.php?r=categorys/remove
2012/04/06 17:22:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "remove".' in E:\pro\xampp\htdocs\yii\framework\web\CController.php:477
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(262): CController->missingAction('remove')
#1 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CController->run('remove')
#2 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('categorys/remov...')
#3 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#4 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/cms/admin/index.php?r=categorys/remove
2012/04/06 17:22:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "remove".' in E:\pro\xampp\htdocs\yii\framework\web\CController.php:477
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(262): CController->missingAction('remove')
#1 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CController->run('remove')
#2 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('categorys/remov...')
#3 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#4 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/cms/admin/index.php?r=categorys/remove
2012/04/06 17:23:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "remove".' in E:\pro\xampp\htdocs\yii\framework\web\CController.php:477
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(262): CController->missingAction('remove')
#1 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CController->run('remove')
#2 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('categorys/remov...')
#3 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#4 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/cms/admin/index.php?r=categorys/remove
2012/04/06 17:32:58 [error] [php] Undefined index: cid (E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php:69)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CategorysController->runAction()
#1 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CategorysController->runActionWithFilters()
#2 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CategorysController->run()
#3 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#4 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#5 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/index.php?r=categorys/remove
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (69)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/04/06 17:44:21 [error] [php] Undefined variable: model (E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php:35)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CategorysController->runAction()
#1 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CategorysController->runActionWithFilters()
#2 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CategorysController->run()
#3 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#4 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#5 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/index.php?r=categorys/post
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (35)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/04/06 17:45:38 [error] [php] Undefined variable: model (E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php:35)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CategorysController->runAction()
#1 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CategorysController->runActionWithFilters()
#2 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CategorysController->run()
#3 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#4 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#5 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/index.php?r=categorys/post
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (35)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/04/06 17:47:11 [error] [php] Undefined variable: model (E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php:35)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CategorysController->runAction()
#1 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CategorysController->runActionWithFilters()
#2 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CategorysController->run()
#3 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#4 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#5 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/index.php?r=categorys/post
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (35)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/04/06 18:14:20 [error] [php] Undefined variable: model (E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php:35)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CategorysController->runAction()
#1 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CategorysController->runActionWithFilters()
#2 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CategorysController->run()
#3 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#4 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#5 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/index.php?r=categorys/post
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (35)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/04/06 18:15:24 [error] [php] Undefined variable: model (E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php:36)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CategorysController->runAction()
#1 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CategorysController->runActionWithFilters()
#2 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CategorysController->run()
#3 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#4 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#5 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/index.php?r=categorys/post
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (36)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/04/06 18:18:59 [error] [php] Undefined variable: parent (E:\pro\xampp\htdocs\cms\admin\protected\models\Categorys.php:80)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\base\CModel.php(152): CInlineValidator->validate()
#1 E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php(50): Categorys->validate()
#2 E:\pro\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): CategorysController->actionPost()
#3 E:\pro\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams()
#4 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CategorysController->runAction()
#5 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CategorysController->runActionWithFilters()
#6 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CategorysController->run()
#7 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#8 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#9 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/index.php?r=categorys/post
in E:\pro\xampp\htdocs\cms\admin\protected\models\Categorys.php (80)
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (50)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/04/06 18:38:12 [error] [php] Non-static method CActiveRecord::findByPk() should not be called statically (E:\pro\xampp\htdocs\cms\admin\protected\models\Categorys.php:100)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): CategorysController->actionPost()
#1 E:\pro\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams()
#2 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CategorysController->runAction()
#3 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CategorysController->runActionWithFilters()
#4 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CategorysController->run()
#5 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#6 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#7 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/index.php?r=categorys/post
in E:\pro\xampp\htdocs\cms\admin\protected\models\Categorys.php (100)
in E:\pro\xampp\htdocs\cms\admin\protected\models\Categorys.php (100)
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (54)
2012/04/06 18:38:51 [error] [php] Trying to get property of non-object (E:\pro\xampp\htdocs\cms\admin\protected\models\Categorys.php:101)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams()
#1 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CategorysController->runAction()
#2 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CategorysController->runActionWithFilters()
#3 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CategorysController->run()
#4 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#5 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#6 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/index.php?r=categorys/post
in E:\pro\xampp\htdocs\cms\admin\protected\models\Categorys.php (101)
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (54)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/04/06 18:41:18 [error] [php] Trying to get property of non-object (E:\pro\xampp\htdocs\cms\admin\protected\models\Categorys.php:109)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams()
#1 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CategorysController->runAction()
#2 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CategorysController->runActionWithFilters()
#3 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CategorysController->run()
#4 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#5 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#6 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/index.php?r=categorys/post
in E:\pro\xampp\htdocs\cms\admin\protected\models\Categorys.php (109)
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (54)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/04/12 15:52:27 [error] [exception.CException] exception 'CException' with message 'CDbCriteria does not have a method named "campare".' in E:\pro\xampp\htdocs\yii\framework\base\CComponent.php:266
Stack trace:
#0 E:\pro\xampp\htdocs\cms\admin\protected\models\Categorys.php(108): CComponent->__call('campare', Array)
#1 E:\pro\xampp\htdocs\cms\admin\protected\models\Categorys.php(108): CDbCriteria->campare('tree', '2|%')
#2 E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php(54): Categorys::updateTree('2')
#3 E:\pro\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): CategorysController->actionPost()
#4 E:\pro\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#5 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#6 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CController->run('post')
#8 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('categorys/post')
#9 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#10 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/cms/admin/index.php?r=categorys/post&cid=2
2012/04/12 15:56:59 [error] [php] Use of undefined constant ture - assumed 'ture' (E:\pro\xampp\htdocs\cms\admin\protected\models\Categorys.php:108)
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams()
#1 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CategorysController->runAction()
#2 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CategorysController->runActionWithFilters()
#3 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CategorysController->run()
#4 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#5 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#6 E:\pro\xampp\htdocs\cms\admin\index.php(13): CWebApplication->run()
REQUEST_URI=/cms/admin/index.php?r=categorys/post&cid=12
in E:\pro\xampp\htdocs\cms\admin\protected\models\Categorys.php (108)
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (54)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/04/12 16:14:42 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%' at line 1. The SQL statement executed was: SELECT * FROM `wf_categorys` `t` WHERE tree like :tree%.
in E:\pro\xampp\htdocs\cms\admin\protected\models\Categorys.php (111)
in E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php (54)
in E:\pro\xampp\htdocs\cms\admin\index.php (13)
2012/04/12 16:14:42 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%' at line 1. The SQL statement executed was: SELECT * FROM `wf_categorys` `t` WHERE tree like :tree%' in E:\pro\xampp\htdocs\yii\framework\db\CDbCommand.php:518
Stack trace:
#0 E:\pro\xampp\htdocs\yii\framework\db\CDbCommand.php(376): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 E:\pro\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1256): CDbCommand->queryAll()
#2 E:\pro\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1380): CActiveRecord->query(Object(CDbCriteria), true)
#3 E:\pro\xampp\htdocs\cms\admin\protected\models\Categorys.php(111): CActiveRecord->findAll(Object(CDbCriteria))
#4 E:\pro\xampp\htdocs\cms\admin\protected\controllers\CategorysController.php(54): Categorys::updateTree('13')
#5 E:\pro\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): CategorysController->actionPost()
#6 E:\pro\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#7 E:\pro\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#8 E:\pro\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(328): CController->run('post')
#10 E:\pro\xampp\htdocs\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('categorys/post')
#11 E:\pro\xampp\htdocs\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#12 E:\pro\xampp\htdocs\cms\admin\index.php(13): CApplication->run()
#13 {main} REQUEST_URI=/cms/admin/index.php?r=categorys/post&cid=13
